print ()
print ("Nama : Danialin siswo handoyo")
print ("NIM  : I0322031") 
print ()
print ("    Halo teman teman, nama saya Danalin Siswo Handoyo, saya biasa dipanggil Didan, Saya tinggal di Perum Giri Asri blokk AA / No 15 , Greik, Jawa Timur, saya tinggal di daerah perbukitan yang sesuai namanya disebut bukit giri, halaman depan rumah saya sekarang telah menjadi sebuah tempat perkumpulan untuk warga, padahal dulu hanya sebuah hutan yang lebat, di samping kanan rumahku ada jalan tanjakan yang agak curam, dan disamping kiri rumahku ada rumah tetangga")
print ("    Harapan saya sebagai lulusan teknik industri adalah menjadi seorang yang berguna bagi kedua orang tua, menjadi seorang pemimpin perusahaan yang mampu bekerja secara profesional dan peduli terhadap rekan seperjuangan.")